apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260607-234618-vb3h1e2ln2bw-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260607-234618-vb3h1e2ln2bw.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260607-234618-vb3h1e2ln2bw-service
            port:
              number: 80
