apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260607-234618-vb3h1e2ln2bw-service
spec:
  selector:
    app: enterprise-system-20260607-234618-vb3h1e2ln2bw
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
